//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeStoresForms.BikeStoresWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceProduct", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ServiceProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private short ModelYearField;
        
        private decimal ListPriceField;
        
        private int BrandIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public short ModelYear {
            get {
                return this.ModelYearField;
            }
            set {
                if ((this.ModelYearField.Equals(value) != true)) {
                    this.ModelYearField = value;
                    this.RaisePropertyChanged("ModelYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal ListPrice {
            get {
                return this.ListPriceField;
            }
            set {
                if ((this.ListPriceField.Equals(value) != true)) {
                    this.ListPriceField = value;
                    this.RaisePropertyChanged("ListPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int BrandId {
            get {
                return this.BrandIdField;
            }
            set {
                if ((this.BrandIdField.Equals(value) != true)) {
                    this.BrandIdField = value;
                    this.RaisePropertyChanged("BrandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceBrand", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ServiceBrand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandId {
            get {
                return this.BrandIdField;
            }
            set {
                if ((this.BrandIdField.Equals(value) != true)) {
                    this.BrandIdField = value;
                    this.RaisePropertyChanged("BrandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCategory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ServiceCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BikeStoresWebService.BikeStoresWebServiceSoap")]
    public interface BikeStoresWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllServiceProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServiceProducts", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse GetAllServiceProducts(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServiceProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse> GetAllServiceProductsAsync(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.GetByIdResponse GetById(BikeStoresForms.BikeStoresWebService.GetByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetByIdResponse> GetByIdAsync(BikeStoresForms.BikeStoresWebService.GetByIdRequest request);
        
        // CODEGEN: Generating message contract since element name serviceProduct from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.InsertResponse Insert(BikeStoresForms.BikeStoresWebService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.InsertResponse> InsertAsync(BikeStoresForms.BikeStoresWebService.InsertRequest request);
        
        // CODEGEN: Generating message contract since element name serviceProduct from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.UpdateResponse Update(BikeStoresForms.BikeStoresWebService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.UpdateResponse> UpdateAsync(BikeStoresForms.BikeStoresWebService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetAllServiceBrandsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServiceBrands", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsResponse GetAllServiceBrands(BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServiceBrands", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsResponse> GetAllServiceBrandsAsync(BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequest request);
        
        // CODEGEN: Generating message contract since element name GetServiceBrandByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceBrandById", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdResponse GetServiceBrandById(BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceBrandById", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdResponse> GetServiceBrandByIdAsync(BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllServiceCategoriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServiceCategories", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesResponse GetAllServiceCategories(BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServiceCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesResponse> GetAllServiceCategoriesAsync(BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name GetServiceCategoryByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceCategoryById", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdResponse GetServiceCategoryById(BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceCategoryById", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdResponse> GetServiceCategoryByIdAsync(BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllServiceProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllServiceProducts", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequestBody Body;
        
        public GetAllServiceProductsRequest() {
        }
        
        public GetAllServiceProductsRequest(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllServiceProductsRequestBody {
        
        public GetAllServiceProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllServiceProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllServiceProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponseBody Body;
        
        public GetAllServiceProductsResponse() {
        }
        
        public GetAllServiceProductsResponse(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllServiceProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceProduct[] GetAllServiceProductsResult;
        
        public GetAllServiceProductsResponseBody() {
        }
        
        public GetAllServiceProductsResponseBody(BikeStoresForms.BikeStoresWebService.ServiceProduct[] GetAllServiceProductsResult) {
            this.GetAllServiceProductsResult = GetAllServiceProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetById", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetByIdRequestBody Body;
        
        public GetByIdRequest() {
        }
        
        public GetByIdRequest(BikeStoresForms.BikeStoresWebService.GetByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetByIdRequestBody() {
        }
        
        public GetByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetByIdResponseBody Body;
        
        public GetByIdResponse() {
        }
        
        public GetByIdResponse(BikeStoresForms.BikeStoresWebService.GetByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceProduct GetByIdResult;
        
        public GetByIdResponseBody() {
        }
        
        public GetByIdResponseBody(BikeStoresForms.BikeStoresWebService.ServiceProduct GetByIdResult) {
            this.GetByIdResult = GetByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(BikeStoresForms.BikeStoresWebService.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            this.serviceProduct = serviceProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(BikeStoresForms.BikeStoresWebService.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertResponseBody {
        
        public InsertResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(BikeStoresForms.BikeStoresWebService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            this.serviceProduct = serviceProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(BikeStoresForms.BikeStoresWebService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllServiceBrandsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllServiceBrands", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequestBody Body;
        
        public GetAllServiceBrandsRequest() {
        }
        
        public GetAllServiceBrandsRequest(BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllServiceBrandsRequestBody {
        
        public GetAllServiceBrandsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllServiceBrandsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllServiceBrandsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsResponseBody Body;
        
        public GetAllServiceBrandsResponse() {
        }
        
        public GetAllServiceBrandsResponse(BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllServiceBrandsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceBrand[] GetAllServiceBrandsResult;
        
        public GetAllServiceBrandsResponseBody() {
        }
        
        public GetAllServiceBrandsResponseBody(BikeStoresForms.BikeStoresWebService.ServiceBrand[] GetAllServiceBrandsResult) {
            this.GetAllServiceBrandsResult = GetAllServiceBrandsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceBrandByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceBrandById", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequestBody Body;
        
        public GetServiceBrandByIdRequest() {
        }
        
        public GetServiceBrandByIdRequest(BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServiceBrandByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetServiceBrandByIdRequestBody() {
        }
        
        public GetServiceBrandByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceBrandByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceBrandByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdResponseBody Body;
        
        public GetServiceBrandByIdResponse() {
        }
        
        public GetServiceBrandByIdResponse(BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServiceBrandByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceBrand GetServiceBrandByIdResult;
        
        public GetServiceBrandByIdResponseBody() {
        }
        
        public GetServiceBrandByIdResponseBody(BikeStoresForms.BikeStoresWebService.ServiceBrand GetServiceBrandByIdResult) {
            this.GetServiceBrandByIdResult = GetServiceBrandByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllServiceCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllServiceCategories", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequestBody Body;
        
        public GetAllServiceCategoriesRequest() {
        }
        
        public GetAllServiceCategoriesRequest(BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllServiceCategoriesRequestBody {
        
        public GetAllServiceCategoriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllServiceCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllServiceCategoriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesResponseBody Body;
        
        public GetAllServiceCategoriesResponse() {
        }
        
        public GetAllServiceCategoriesResponse(BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllServiceCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceCategory[] GetAllServiceCategoriesResult;
        
        public GetAllServiceCategoriesResponseBody() {
        }
        
        public GetAllServiceCategoriesResponseBody(BikeStoresForms.BikeStoresWebService.ServiceCategory[] GetAllServiceCategoriesResult) {
            this.GetAllServiceCategoriesResult = GetAllServiceCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceCategoryByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceCategoryById", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequestBody Body;
        
        public GetServiceCategoryByIdRequest() {
        }
        
        public GetServiceCategoryByIdRequest(BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServiceCategoryByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetServiceCategoryByIdRequestBody() {
        }
        
        public GetServiceCategoryByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceCategoryByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceCategoryByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdResponseBody Body;
        
        public GetServiceCategoryByIdResponse() {
        }
        
        public GetServiceCategoryByIdResponse(BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServiceCategoryByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceCategory GetServiceCategoryByIdResult;
        
        public GetServiceCategoryByIdResponseBody() {
        }
        
        public GetServiceCategoryByIdResponseBody(BikeStoresForms.BikeStoresWebService.ServiceCategory GetServiceCategoryByIdResult) {
            this.GetServiceCategoryByIdResult = GetServiceCategoryByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BikeStoresWebServiceSoapChannel : BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BikeStoresWebServiceSoapClient : System.ServiceModel.ClientBase<BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap>, BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap {
        
        public BikeStoresWebServiceSoapClient() {
        }
        
        public BikeStoresWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BikeStoresWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BikeStoresWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BikeStoresWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetAllServiceProducts(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest request) {
            return base.Channel.GetAllServiceProducts(request);
        }
        
        public BikeStoresForms.BikeStoresWebService.ServiceProduct[] GetAllServiceProducts() {
            BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest inValue = new BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequestBody();
            BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetAllServiceProducts(inValue);
            return retVal.Body.GetAllServiceProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetAllServiceProductsAsync(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest request) {
            return base.Channel.GetAllServiceProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse> GetAllServiceProductsAsync() {
            BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest inValue = new BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequestBody();
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetAllServiceProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.GetByIdResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetById(BikeStoresForms.BikeStoresWebService.GetByIdRequest request) {
            return base.Channel.GetById(request);
        }
        
        public BikeStoresForms.BikeStoresWebService.ServiceProduct GetById(int id) {
            BikeStoresForms.BikeStoresWebService.GetByIdRequest inValue = new BikeStoresForms.BikeStoresWebService.GetByIdRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetByIdRequestBody();
            inValue.Body.id = id;
            BikeStoresForms.BikeStoresWebService.GetByIdResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetById(inValue);
            return retVal.Body.GetByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetByIdResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetByIdAsync(BikeStoresForms.BikeStoresWebService.GetByIdRequest request) {
            return base.Channel.GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetByIdResponse> GetByIdAsync(int id) {
            BikeStoresForms.BikeStoresWebService.GetByIdRequest inValue = new BikeStoresForms.BikeStoresWebService.GetByIdRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetByIdRequestBody();
            inValue.Body.id = id;
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.InsertResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.Insert(BikeStoresForms.BikeStoresWebService.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public void Insert(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            BikeStoresForms.BikeStoresWebService.InsertRequest inValue = new BikeStoresForms.BikeStoresWebService.InsertRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.InsertRequestBody();
            inValue.Body.serviceProduct = serviceProduct;
            BikeStoresForms.BikeStoresWebService.InsertResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).Insert(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.InsertResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.InsertAsync(BikeStoresForms.BikeStoresWebService.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.InsertResponse> InsertAsync(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            BikeStoresForms.BikeStoresWebService.InsertRequest inValue = new BikeStoresForms.BikeStoresWebService.InsertRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.InsertRequestBody();
            inValue.Body.serviceProduct = serviceProduct;
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.UpdateResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.Update(BikeStoresForms.BikeStoresWebService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            BikeStoresForms.BikeStoresWebService.UpdateRequest inValue = new BikeStoresForms.BikeStoresWebService.UpdateRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.UpdateRequestBody();
            inValue.Body.serviceProduct = serviceProduct;
            BikeStoresForms.BikeStoresWebService.UpdateResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.UpdateResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.UpdateAsync(BikeStoresForms.BikeStoresWebService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.UpdateResponse> UpdateAsync(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            BikeStoresForms.BikeStoresWebService.UpdateRequest inValue = new BikeStoresForms.BikeStoresWebService.UpdateRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.UpdateRequestBody();
            inValue.Body.serviceProduct = serviceProduct;
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetAllServiceBrands(BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequest request) {
            return base.Channel.GetAllServiceBrands(request);
        }
        
        public BikeStoresForms.BikeStoresWebService.ServiceBrand[] GetAllServiceBrands() {
            BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequest inValue = new BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequestBody();
            BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetAllServiceBrands(inValue);
            return retVal.Body.GetAllServiceBrandsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetAllServiceBrandsAsync(BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequest request) {
            return base.Channel.GetAllServiceBrandsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsResponse> GetAllServiceBrandsAsync() {
            BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequest inValue = new BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetAllServiceBrandsRequestBody();
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetAllServiceBrandsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetServiceBrandById(BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequest request) {
            return base.Channel.GetServiceBrandById(request);
        }
        
        public BikeStoresForms.BikeStoresWebService.ServiceBrand GetServiceBrandById(int id) {
            BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequest inValue = new BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequestBody();
            inValue.Body.id = id;
            BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetServiceBrandById(inValue);
            return retVal.Body.GetServiceBrandByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetServiceBrandByIdAsync(BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequest request) {
            return base.Channel.GetServiceBrandByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdResponse> GetServiceBrandByIdAsync(int id) {
            BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequest inValue = new BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetServiceBrandByIdRequestBody();
            inValue.Body.id = id;
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetServiceBrandByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetAllServiceCategories(BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequest request) {
            return base.Channel.GetAllServiceCategories(request);
        }
        
        public BikeStoresForms.BikeStoresWebService.ServiceCategory[] GetAllServiceCategories() {
            BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequest inValue = new BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequestBody();
            BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetAllServiceCategories(inValue);
            return retVal.Body.GetAllServiceCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetAllServiceCategoriesAsync(BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequest request) {
            return base.Channel.GetAllServiceCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesResponse> GetAllServiceCategoriesAsync() {
            BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequest inValue = new BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetAllServiceCategoriesRequestBody();
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetAllServiceCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetServiceCategoryById(BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequest request) {
            return base.Channel.GetServiceCategoryById(request);
        }
        
        public BikeStoresForms.BikeStoresWebService.ServiceCategory GetServiceCategoryById(int id) {
            BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequest inValue = new BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequestBody();
            inValue.Body.id = id;
            BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetServiceCategoryById(inValue);
            return retVal.Body.GetServiceCategoryByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetServiceCategoryByIdAsync(BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequest request) {
            return base.Channel.GetServiceCategoryByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdResponse> GetServiceCategoryByIdAsync(int id) {
            BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequest inValue = new BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetServiceCategoryByIdRequestBody();
            inValue.Body.id = id;
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetServiceCategoryByIdAsync(inValue);
        }
    }
}
