//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeStoresForms.BikeStoresWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceProduct", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ServiceProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private short ModelYearField;
        
        private decimal ListPriceField;
        
        private int BrandIdField;
        
        private int CategoryIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public short ModelYear {
            get {
                return this.ModelYearField;
            }
            set {
                if ((this.ModelYearField.Equals(value) != true)) {
                    this.ModelYearField = value;
                    this.RaisePropertyChanged("ModelYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal ListPrice {
            get {
                return this.ListPriceField;
            }
            set {
                if ((this.ListPriceField.Equals(value) != true)) {
                    this.ListPriceField = value;
                    this.RaisePropertyChanged("ListPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int BrandId {
            get {
                return this.BrandIdField;
            }
            set {
                if ((this.BrandIdField.Equals(value) != true)) {
                    this.BrandIdField = value;
                    this.RaisePropertyChanged("BrandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BikeStoresWebService.BikeStoresWebServiceSoap")]
    public interface BikeStoresWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllServiceProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServiceProducts", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse GetAllServiceProducts(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllServiceProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse> GetAllServiceProductsAsync(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.GetByIdResponse GetById(BikeStoresForms.BikeStoresWebService.GetByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetByIdResponse> GetByIdAsync(BikeStoresForms.BikeStoresWebService.GetByIdRequest request);
        
        // CODEGEN: Generating message contract since element name serviceProduct from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.InsertResponse Insert(BikeStoresForms.BikeStoresWebService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.InsertResponse> InsertAsync(BikeStoresForms.BikeStoresWebService.InsertRequest request);
        
        // CODEGEN: Generating message contract since element name serviceProduct from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        BikeStoresForms.BikeStoresWebService.UpdateResponse Update(BikeStoresForms.BikeStoresWebService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.UpdateResponse> UpdateAsync(BikeStoresForms.BikeStoresWebService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllServiceProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllServiceProducts", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequestBody Body;
        
        public GetAllServiceProductsRequest() {
        }
        
        public GetAllServiceProductsRequest(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllServiceProductsRequestBody {
        
        public GetAllServiceProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllServiceProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllServiceProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponseBody Body;
        
        public GetAllServiceProductsResponse() {
        }
        
        public GetAllServiceProductsResponse(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllServiceProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceProduct[] GetAllServiceProductsResult;
        
        public GetAllServiceProductsResponseBody() {
        }
        
        public GetAllServiceProductsResponseBody(BikeStoresForms.BikeStoresWebService.ServiceProduct[] GetAllServiceProductsResult) {
            this.GetAllServiceProductsResult = GetAllServiceProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetById", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetByIdRequestBody Body;
        
        public GetByIdRequest() {
        }
        
        public GetByIdRequest(BikeStoresForms.BikeStoresWebService.GetByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetByIdRequestBody() {
        }
        
        public GetByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.GetByIdResponseBody Body;
        
        public GetByIdResponse() {
        }
        
        public GetByIdResponse(BikeStoresForms.BikeStoresWebService.GetByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceProduct GetByIdResult;
        
        public GetByIdResponseBody() {
        }
        
        public GetByIdResponseBody(BikeStoresForms.BikeStoresWebService.ServiceProduct GetByIdResult) {
            this.GetByIdResult = GetByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(BikeStoresForms.BikeStoresWebService.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            this.serviceProduct = serviceProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(BikeStoresForms.BikeStoresWebService.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertResponseBody {
        
        public InsertResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(BikeStoresForms.BikeStoresWebService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            this.serviceProduct = serviceProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public BikeStoresForms.BikeStoresWebService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(BikeStoresForms.BikeStoresWebService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BikeStoresWebServiceSoapChannel : BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BikeStoresWebServiceSoapClient : System.ServiceModel.ClientBase<BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap>, BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap {
        
        public BikeStoresWebServiceSoapClient() {
        }
        
        public BikeStoresWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BikeStoresWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BikeStoresWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BikeStoresWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetAllServiceProducts(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest request) {
            return base.Channel.GetAllServiceProducts(request);
        }
        
        public BikeStoresForms.BikeStoresWebService.ServiceProduct[] GetAllServiceProducts() {
            BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest inValue = new BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequestBody();
            BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetAllServiceProducts(inValue);
            return retVal.Body.GetAllServiceProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetAllServiceProductsAsync(BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest request) {
            return base.Channel.GetAllServiceProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetAllServiceProductsResponse> GetAllServiceProductsAsync() {
            BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest inValue = new BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetAllServiceProductsRequestBody();
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetAllServiceProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.GetByIdResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetById(BikeStoresForms.BikeStoresWebService.GetByIdRequest request) {
            return base.Channel.GetById(request);
        }
        
        public BikeStoresForms.BikeStoresWebService.ServiceProduct GetById(int id) {
            BikeStoresForms.BikeStoresWebService.GetByIdRequest inValue = new BikeStoresForms.BikeStoresWebService.GetByIdRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetByIdRequestBody();
            inValue.Body.id = id;
            BikeStoresForms.BikeStoresWebService.GetByIdResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetById(inValue);
            return retVal.Body.GetByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetByIdResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.GetByIdAsync(BikeStoresForms.BikeStoresWebService.GetByIdRequest request) {
            return base.Channel.GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.GetByIdResponse> GetByIdAsync(int id) {
            BikeStoresForms.BikeStoresWebService.GetByIdRequest inValue = new BikeStoresForms.BikeStoresWebService.GetByIdRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.GetByIdRequestBody();
            inValue.Body.id = id;
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.InsertResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.Insert(BikeStoresForms.BikeStoresWebService.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public void Insert(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            BikeStoresForms.BikeStoresWebService.InsertRequest inValue = new BikeStoresForms.BikeStoresWebService.InsertRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.InsertRequestBody();
            inValue.Body.serviceProduct = serviceProduct;
            BikeStoresForms.BikeStoresWebService.InsertResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).Insert(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.InsertResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.InsertAsync(BikeStoresForms.BikeStoresWebService.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.InsertResponse> InsertAsync(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            BikeStoresForms.BikeStoresWebService.InsertRequest inValue = new BikeStoresForms.BikeStoresWebService.InsertRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.InsertRequestBody();
            inValue.Body.serviceProduct = serviceProduct;
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BikeStoresForms.BikeStoresWebService.UpdateResponse BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.Update(BikeStoresForms.BikeStoresWebService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            BikeStoresForms.BikeStoresWebService.UpdateRequest inValue = new BikeStoresForms.BikeStoresWebService.UpdateRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.UpdateRequestBody();
            inValue.Body.serviceProduct = serviceProduct;
            BikeStoresForms.BikeStoresWebService.UpdateResponse retVal = ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.UpdateResponse> BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap.UpdateAsync(BikeStoresForms.BikeStoresWebService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<BikeStoresForms.BikeStoresWebService.UpdateResponse> UpdateAsync(BikeStoresForms.BikeStoresWebService.ServiceProduct serviceProduct) {
            BikeStoresForms.BikeStoresWebService.UpdateRequest inValue = new BikeStoresForms.BikeStoresWebService.UpdateRequest();
            inValue.Body = new BikeStoresForms.BikeStoresWebService.UpdateRequestBody();
            inValue.Body.serviceProduct = serviceProduct;
            return ((BikeStoresForms.BikeStoresWebService.BikeStoresWebServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
